# TODO: Remove this file if using something other than GitHub Actions for CI.
name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0

      - name: Install
        run: npm ci

      - name: Build and test
        run: npm test

      - name: Audit installed packages (info only)
        run: npm audit || true
